### ISSUE TITLE
hintID, CORS 이슈, 중복된 키워드 문제

### ISSUE THREAD

**Issue by JangJua** [LEEMINJOO/WRITE-ME#24]
[GET] /api/posts/hint?keywordID={keywordID} 
CORS 문제 해결해야 함 

hintID - auto increment로 

[GET] /api/posts/distinctKeyword?categoryID={categoryID}
여전히 중복된 키워드를 가져옴

**Comment by LEEMINJOO** [comment]
중복 키워드 가져온다는거는 ID 다른데 Name이 겹치는경우 말씀하시는건가요?
