### ISSUE TITLE
기능 리스트업

### ISSUE THREAD

**Issue by LEEMINJOO** [LEEMINJOO/WRITE-ME#3]
회원가입/로그인 
모든 서비스는 로그인이 되어있어야 접근 가능
로그인이 안 되어있으면 로그인 페이지로 넘어감 

* 정치 / 경제 / 사회 / 세계 / IT과학 … 5개의 카테고리별 api GET
  * 지난 키워드를 불러오기 (여러개)
    * api/keywords/categoryID
  * 오늘의 키워드를 불러오기
    *  api/keywords/categoryID/date
* 글을 키워드별로 볼 수 있는 api GET
  * 좋아요 순
    * api/posts/keyword/like/keywordID
  * 최신 순
    * api/posts/keyword/recent/keywordID
* 글을 사용자별로 볼 수 있는 api GET
  * api/posts/user/userID
* 글 작성 api POST
  * api/post/postID
* 좋아요 누르기 api POST
  * api/like/postID

**Comment by LEEMINJOO** [comment]
지난 키워드에도 글을 쓸 수 있게 할것인가?

**Comment by LEEMINJOO** [comment]
* 키워드 추출 
  * 네이버에서 각 카테고리별 상위 30개 기사 크롤링 - bs4
  * 30개 기사 중 주요 키워드 추출 - TF-IDF
  * 키워드를 DB에 저장 - pymysql

* 세부 키워드 추출
  * 해당 키워드를 가지고 최신순 검색
  * 최신 기사의 제목에서 키워드 추출
  * 빈도기준으로 3,4개로 추림

**Comment by JangJua** [comment]
로그인/회원가입 관련 
POST /api/register/local: 회원가입 API
POST /api/login/local: 로그인 API
GET /exists/:key/:value: 이메일 / 아이디 중복확인
POST /logout: 로그아웃
